[package]
edition = "2021"
name = "database"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = {version = "1.4", features = ["mysql", "chrono"]}
uuid = {version = "0.8", features = ["v4"]}
chrono = "0.4"